### ISSUE TITLE
atomicInt64Limiter WithoutSlack doesn't block

### ISSUE THREAD

**Issue by twelsh-aw** [uber-go/ratelimit#90] opened 2022-06-09 16:50 UTC
First off thanks for the library :)

Saw that a new rate limiter was introduced that benchmarked a lot better and pulled it down to try it out.

Noticed that when running WithoutSlack, it just allows everything through instead of waiting because all subsequent Take() calls fall into the `case now-timeOfNextPermissionIssue > int64(t.maxSlack)`

Easiest way to repro is using your `example_test.go`:

- Using `rl := ratelimit.New(100)` (slack=10):
```shell
go test -run Example -count=1
=== RUN   Example
--- PASS: Example (0.09s)
PASS
ok      command-line-arguments  0.207s
```

- Using `rl := ratelimit.New(100, ratelimit.WithoutSlack)`
```shell
go test -run Example -count=1   
--- FAIL: Example (0.01s)
got:
1 10ms
2 775µs
3 3µs
4 2µs
5 10µs
6 2µs
7 2µs
8 2µs
9 2µs
want:
1 10ms
2 10ms
3 10ms
4 10ms
5 10ms
6 10ms
7 10ms
8 10ms
9 10ms
FAIL
FAIL    command-line-arguments  0.126s
FAIL
```

- Using 0.2.0 `rl :=newAtomicBased(100, WithoutSlack)`
```shell
go test -run Example -count=1
PASS
ok      go.uber.org/ratelimit   0.323s
```

I am not 100% sure why the other units with mocked clocks are passing, but your example test and my application tests fail consistently with this new limiter. On darwin if that helps.

**Comment by storozhukBM** [comment] 2022-06-09 17:26
@twelsh-aw 
Yes, the issue is definitely there, I have a quick fix for it, but I also want to spend a bit more time to figure out why our tests don't catch that issue.

**Comment by storozhukBM** [comment] 2022-06-09 18:30
@rabbbit
I figured out that our tests continue to pass even if I break currently existing implementation.
For example if you change `ratelimit_test.go:108` to `t.clock.Sleep(interval-interval)` tests will still pass.

**Comment by storozhukBM** [comment] 2022-06-09 19:10
@rabbbit
Further findings. Tests do not able to detect issues because with mock clock, literally time, freezes between `Take()` calls, to when we check `now.Sub(oldState.last)` in `atomicLimiter` or when we check `now-timeOfNextPermissionIssue` in `atomicInt64Limiter` it always returns 0

**Comment by storozhukBM** [comment] 2022-06-09 19:14
@rabbbit 
If we add `r.clock.Add(time.Microsecond)` between takes in `(r *runnerImpl) startTaking` tests start to detect issues.
The problem with that is that we call `startTaking` in different goroutines and  "github.com/benbjohnson/clock" is not concurrently safe, so race detector fails when it finds some races inside mockClock state.

So we either should find concurrent mock clock implementation, or fix "github.com/benbjohnson/clock" or write our own.

**Comment by storozhukBM** [comment] 2022-06-09 19:26
@rabbbit agree, I'll look at possible options with time mocking and will fix our tests in the following PR

**Comment by storozhukBM** [comment] 2022-06-27 20:40
@rabbbit I created a new PR as discussed https://github.com/uber-go/ratelimit/pull/93

**Comment by storozhukBM** [comment] 2022-07-02 21:02
@rabbbit

PR with fix for this issue https://github.com/uber-go/ratelimit/pull/95

Also you can see on tests approach PR that it is able to detect this bug

**Comment by rabbbit** [comment] 2022-07-05 06:33
Ack. This is pretty high on my priority list, will try to get to this soon. Again, sorry for the delay.

**Comment by storozhukBM** [comment] 2022-10-30 16:16
@rabbbit We already have a fix in place. What do you think about making atomicInt64Limiter a default implementation again and allowing people to have a try before cutting a new release tag? Or we can make this implementation public so that users can instantiate it. I'd like the new testing approach to be merged first, but if you're unsure about it, we can skip it for now.

**Comment by rabbbit** [comment] 2022-10-30 18:34
The new atomic version seems to perform so much better than it feels we should enable it.

However, after that, we might just have to declare a code freeze until someone else has more cycles for reviews. Sadly this includes the new time-testing, would need to look at this in much more detail before merging in.

**Comment by storozhukBM** [comment] 2022-10-30 18:37
@rabbbit OK, so should I make a PR now?

**Comment by rabbbit** [comment] 2022-10-31 00:05
SGTM

**Comment by storozhukBM** [comment] 2022-10-31 00:55
@rabbbit 
Please take a look
https://github.com/uber-go/ratelimit/pull/101

**Comment by rabbbit** [comment] 2022-10-31 03:14
Closing as fixed - we reverted the bad change in #91, @storozhukBM fixed it in #95, but we were defaulting to the old implementation. #101 makes the new (faster) implementation the default.

**Comment by storozhukBM** [comment] 2022-10-31 03:14
@twelsh-aw  this change is now merged, can you please try again give us your feedback

**Closed by rabbbit** 2022-10-31 03:14 UTC

**Comment by storozhukBM** [comment] 2022-10-31 03:15
thank you @rabbbit
